digital_library/accounts/urls.py
from django.urls import path

from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('', redirect_view),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/person/', PersonSignUpView.as_view(), name='person-signup'),
    path('signup/library/', LibrarySignUpView.as_view(), name='library-signup'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/library/<int:pk>/update/', LibraryProfileUpdateView.as_view(), name='library-update'),
    path('profile/add-library-cards', LibraryCardsCreateView.as_view(), name='library-cards-create'),
    path('profile/library-cards/list', LibraryCardsList.as_view(), name='library-cards-list'),
    path('profile/library-cards/<int:pk>/update', LibraryCardsUpdate.as_view(), name='library-cards-update'),
    path('profile/library-cards/<int:pk>/delete', LibraryCardsDelete.as_view(), name='library-cards-delete'),
]

digital_library/digital_lending/urls.py
from django.urls import path

from .views import *

app_name = 'digital_lending'

urlpatterns = [
    path('author/create', AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update', AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/detail', AuthorDetail.as_view(), name='author-detail'),
    path('book/create', BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update', BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/detail', BookDetail.as_view(), name='book-detail'),
    path('category/<int:pk>/detail', CategoryDetail.as_view(), name='category-detail'),
    path('publisher/create', PublisherCreate.as_view(), name='publisher-create'),
    path('publisher/<int:pk>/update', PublisherUpdate.as_view(), name='publisher-update'),
    path('publisher/<int:pk>/detail', PublisherDetail.as_view(), name='publisher-detail'),
    path('edition/create', EditionCreate.as_view(), name='edition-create'),
    path('periodical/create', PeriodicalCreate.as_view(), name='periodical-create'),
    path('periodical/<int:pk>/issue/create', PeriodicalIssueCreate.as_view(), name='issue-create'),
    path('edition/<int:pk>/update', EditionUpdate.as_view(), name='edition-update'),
    path('periodical/<int:pk>/update', PeriodicalUpdate.as_view(), name='periodical-update'),
    path('catalogue/', EditionList.as_view(), name='editions'),
    path('periodicals/', PeriodicalList.as_view(), name='periodicals'),
    path('edition/<int:pk>/detail', EditionDetail.as_view(), name='edition-detail'),
    path('edition/<int:pk>/copy-create', CopyCreate.as_view(), name='copy-create'),
    path('edition/<int:pk>/copies', CopyList.as_view(), name='copies'),
    path('edition/<int:pk>/choose-copy', ChooseCopyToLendView.as_view(), name='choose-copy'),
    path('library_catalogue', LibraryEditionsList.as_view(), name='library-catalogue'),
    path('library_periodicals', LibraryPeriodicalsList.as_view(), name='library-periodicals'),
    path('copy/<int:pk>/update', CopyUpdate.as_view(), name='copy-update'),
    path('copy/<int:pk>/delete', CopyDelete.as_view(), name='copy-delete'),
    path('periodical/<int:pk>/issues', PeriodicalIssueList.as_view(), name='periodical-issues'),
    path('issue/<int:pk>/update', PeriodicalIssueUpdate.as_view(), name='periodical-issue-update'),
    path('issue/<int:pk>/delete', PeriodicalIssueDelete.as_view(), name='periodical-issue-delete'),
    path('edition/<int:pk>/lend', LendBookView.as_view(), name='edition-lend'),
    path('edition/<int:pk>/reservation', BookReservationView.as_view(), name='edition-reservation'),
    path('edition/<int:pk>/favorite', BookFavoriteView.as_view(), name='edition-favorite'),
    path('edition/<int:pk>/add-to-list', AddBookToListView.as_view(), name='add-book-to-list'),
    path('edition/<int:pk>/delete-from-list', DeleteBookInList.as_view(), name='delete-book-from-list'),
    path('book-history', PersonBookHistoryList.as_view(), name='book-history'),
    path('book-reservations', PersonReservationList.as_view(), name='book-reservations'),
    path('book-reservations/<int:pk>/delete', ReservationDelete.as_view(), name='book-reservation-delete'),
    path('favorite-books', PersonFavoriteBooksList.as_view(), name='favorite-books'),
    path('favorite-books/<int:pk>/delete', FavoriteBookDelete.as_view(), name='favorite-book-delete'),
    path('book-list/create', BookListCreate.as_view(), name='book-list-create'),
    path('my-book-lists', UserBookLists.as_view(), name='my-book-lists'),
    path('my-saved-book-lists', UserSavedBookLists.as_view(), name='my-saved-book-lists'),
    path('book-lists', BookLists.as_view(), name='book-lists'),
    path('book-list/<int:pk>/detail', BookListDetail.as_view(), name='book-list-detail'),
    path('book-list/<int:pk>/update', BookListUpdate.as_view(), name='book-list-update'),
    path('book-list/<int:pk>/delete', BookListDelete.as_view(), name='book-list-delete'),
    path('book-list/<int:pk>/save', SaveBookListView.as_view(), name='book-list-save'),
    path('edition/<int:pk>/suggest-purchase', SuggestPurchaseView.as_view(), name='suggest-purchase'),
    path('purchase-suggestions/', LibraryPurchaseSuggestionsList.as_view(), name='purchase-suggestions'),
]

digital_library/digital_library/urls.py
import logging

from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from .views import Homepage, NotFound

_logger = logging.getLogger(__name__)

urlpatterns = [
    path('', Homepage.as_view(), name='home'),
    path('404-not-found', NotFound.as_view(), name='404-not-found'),
    path('reviews/', include('reviews.urls')),
    path('site/', include('digital_lending.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

digital_library/reviews/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'reviews'

urlpatterns = [
    path('edition/<int:pk>/reviews', ReviewListView.as_view(), name="review-list"),
    path('my-reviews', PersonReviewList.as_view(), name='my-reviews'),
    path('<int:pk>/detail', ReviewDetail.as_view(), name="review-detail"),
    path('edition/<int:pk>/add-review', ReviewCreateView.as_view(), name="review-create"),
    path('<int:pk>/update-review', ReviewUpdateView.as_view(), name="review-update"),
    path('<int:pk>/delete-review', ReviewDeleteView.as_view(), name="review-delete"),
    path('<int:pk>/upvote', ReviewUpvoteView.as_view(), name="review-upvote"),
    path('<int:pk>/downvote', ReviewDownvoteView.as_view(), name="review-downvote"),
]

digital_library/reviews/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from digital_lending.models import Edition
from accounts.models import User


class Review(models.Model):
    author = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE)
    book = models.ForeignKey(Edition, blank=False, null=False, on_delete=models.CASCADE)
    rating = models.IntegerField(
        validators=[MaxValueValidator(10), MinValueValidator(1)],
        blank=False,
        null=False
    )

    text = models.TextField(max_length=9000)
    date_created = models.DateTimeField(auto_now_add=True, editable=False)
    upvotes = models.ManyToManyField(User, symmetrical=False, related_name='upvotes', blank=True)
    downvotes = models.ManyToManyField(User, symmetrical=False, related_name='downvotes', blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["author", "book"],
                name="Each user can review a book only once",
            )
        ]

digital_library/reviews/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from .models import Review


class ReviewCreateForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = 'create_review_crispy_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Submit'))
    helper.inputs[0].field_classes = 'btn btn-success'

    class Meta(forms.ModelForm):
        model = Review
        fields = ("rating", "text")
        labels = {
            'rating': 'Voto',
            'text': 'Testo',
        }


class ReviewUpdateForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = 'update_review_crispy_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Submit'))
    helper.inputs[0].field_classes = 'btn btn-success'

    class Meta(forms.ModelForm):
        model = Review
        fields = ("rating", "text")
        labels = {
            'rating': 'Voto',
            'text': 'Testo',
        }

digital_library/reviews/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from digital_lending.models import Edition
from .forms import ReviewCreateForm, ReviewUpdateForm
from .models import Review


class ReviewListView(ListView):
    model = Review
    template_name = 'reviews/list.html'
    paginate_by = 6

    def get_queryset(self):
        reviews = Review.objects.filter(book=self.kwargs['pk'])

        order = self.request.GET.get("sort")
        if order == "oldest":
            reviews = reviews.order_by("-date_created")
        elif order == "best_rating":
            reviews = reviews.order_by("-rating")
        elif order == "worst_rating":
            reviews = reviews.order_by("rating")
        else:
            reviews = reviews.order_by("date_created")

        return reviews

    def get_context_data(self, **kwargs):
        context = super(ReviewListView, self).get_context_data(**kwargs)
        context['edition'] = Edition.objects.get(isbn_digital=self.kwargs['pk'])
        context['sort'] = self.request.GET.get("sort")
        return context


class PersonReviewList(ListView):
    paginate_by = 6
    model = Review
    template_name = 'reviews/personal_list.html'

    def get_queryset(self):
        reviews = Review.objects.filter(author_id=self.request.user.id).order_by('-date_created')
        return reviews


class ReviewCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = ReviewCreateForm
    template_name = "reviews/create.html"
    model = Review
    success_message = 'Recensione creata con successo!'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('reviews:review-list', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super(ReviewCreateView, self).get_context_data(**kwargs)
        context['edition'] = Edition.objects.get(isbn_digital=self.kwargs['pk'])
        return context

    def get_form(self):
        form = super().get_form()
        form.instance.book = Edition.objects.get(isbn_digital=self.kwargs['pk'])
        return form

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        try:
            return super().post(request, *args, **kwargs)
        except IntegrityError:
            messages.add_message(request, messages.ERROR,
                                 'Hai già scritto una recensione per questa edizione.')
            return render(request, template_name=self.template_name, context=self.get_context_data())


class ReviewDetail(DetailView):
    model = Review
    template_name = 'reviews/detail.html'

    def get_context_data(self, **kwargs):
        context = super(ReviewDetail, self).get_context_data(**kwargs)
        context['upvotes'] = Review.objects.get(id=self.kwargs['pk']).upvotes.all().count()
        context['downvotes'] = Review.objects.get(id=self.kwargs['pk']).downvotes.all().count()
        return context


class ReviewUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Review
    template_name = 'reviews/update.html'
    form_class = ReviewUpdateForm
    success_message = 'Recensione aggiornata con successo!'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('reviews:review-detail', kwargs={'pk': pk})

    def get_object(self, *args, **kwargs):
        obj = super(ReviewUpdateView, self).get_object(*args, **kwargs)
        if not obj.author_id == self.request.user.id:
            raise PermissionDenied
        return obj


class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    model = Review
    template_name = 'reviews/delete.html'
    success_message = 'Recensione eliminata con successo!'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('reviews:my-reviews')

    def delete(self, request, *args, **kwargs):
        obj = super(ReviewDeleteView, self).delete(request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return obj

    def get_object(self, *args, **kwargs):
        obj = super(ReviewDeleteView, self).get_object(*args, **kwargs)
        if not obj.author_id == self.request.user.id:
            raise PermissionDenied
        return obj


class ReviewUpvoteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        review = Review.objects.get(id=self.kwargs['pk'])
        if review.upvotes.filter(id=request.user.id).exists():
            review.upvotes.remove(request.user)
        else:
            review.upvotes.add(request.user)
            if review.downvotes.filter(id=request.user.id).exists():
                review.downvotes.remove(request.user)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ReviewDownvoteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        review = Review.objects.get(id=self.kwargs['pk'])
        if review.downvotes.filter(id=request.user.id).exists():
            review.downvotes.remove(request.user)
        else:
            review.downvotes.add(request.user)
            if review.upvotes.filter(id=request.user.id).exists():
                review.upvotes.remove(request.user)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

digital_library/reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Scrivi una recensione per {{ edition.book.title }}{% endblock %}

{% block content %}
    {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             <b>{{ message|safe }}</b>
         </div>
     {% endfor %}
    {% endif %}

    <h1><b>Scrivi una recensione per {{ edition.book.title }}</b></h1>
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <br>
        <a href="{% url 'digital_lending:edition-detail' edition.pk %}">Annulla</a>
        <input type="submit" value="Conferma">
    </form>
{% endblock %}

digital_library/reviews/templates/reviews/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Elimina recensione{% endblock %}

{% block content %}
    <h1><b>Elimina recensione</b></h1>
    <br>
    <h4>Confermi di voler eliminare questa recensione?</h4>
    <h5><b>Libro:</b> {{ object.book.book.title }}</h5>
    <h5><b>Scritta in data:</b> {{ object.date_created|date }}</h5>
    <h5><b>Testo: </b>{{ object.text }}</h5>
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <br>
        <a href="{% url 'reviews:review-detail' object.pk %}">Annulla</a>
        <input type="submit" value="Conferma">
    </form>
{% endblock %}

digital_library/reviews/templates/reviews/detail.html
{% extends 'base.html' %}

{% block title %}Recensione: {{ object.book.book.title }}{% endblock %}

{% block content %}
    {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
    {% endif %}

    <h1><b>Recensione: <a href="{% url 'digital_lending:edition-detail' object.book.pk %}">"{{ object.book.book.title }}"</a></b></h1>
    <h3><a href="{% url 'accounts:profile' object.author.pk %}">{{ object.author.username }}</a></h3>
    <br>
    <h5><b>Voto:</b> {{ object.rating }}</h5>
    <br>
    <p>"<i>{{ object.text }}</i>"</p>
    <br>
    <p><b>{{ upvotes }} upvotes, {{ downvotes }} downvotes</b></p>
    <br>
    {% if user.is_authenticated %}
        {% if user != object.author %}
        <form method="POST" action="{% url 'reviews:review-upvote' object.pk %}" class="form-check-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-success" >Upvote</button>
        </form>
        <form method="POST" action="{% url 'reviews:review-downvote' object.pk %}" class="form-check-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger" >Downvote</button>
        </form>
        <br>
        {% elif user == object.author %}
            <a href="{% url 'reviews:review-update' object.pk %}" class="w3-button w3-teal w3-round-large">Aggiorna recensione</a>
            <br><br>
            <a href="{% url 'reviews:review-delete' object.pk %}" class="w3-button w3-teal w3-round-large">Elimina recensione</a>
        {% endif %}
    {% endif %}
{% endblock %}

digital_library/reviews/templates/reviews/list.html
{% extends 'base_list.html' %}

{% block list_title %}Recensioni: {{ object_list.0.book.book.title }}{% endblock %}
{% block content_title %}Recensioni: <b>{{ object_list.0.book.book.title }}</b>{% endblock %}

{% block thead %}
    {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
    {% endif %}

    <th>Utente</th>
    <th>Voto
        {% if sort == "worst_rating" or "" %}
            <a href="{% url 'reviews:review-list' edition.pk %}?sort=best_rating">▼</a>
        {% else %}
            <a href="{% url 'reviews:review-list' edition.pk %}?sort=worst_rating">▲</a>
    {% endif %}
    </th>
    <th>Testo</th>
    <th>Data
        {% if sort == "oldest" or "" %}
            <a href="{% url 'reviews:review-list' edition.pk %}?sort=newest">▼</a>
        {% else %}
            <a href="{% url 'reviews:review-list' edition.pk %}?sort=oldest">▲</a>
    {% endif %}
    </th>
    <th>Dettaglio</th>
{% endblock %}

{% block tbody %}
    {% for review in page_obj %}
        <tr>
            <td><a href="{% url 'accounts:profile' review.author.pk %}">{{ review.author.username }}</a></td>
            <td>{{ review.rating }}</td>
            <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:1px;">{{ review.text }}</td>
            <td>{{ review.date_created|date }}</td>
            <td><a href="{% url 'reviews:review-detail' review.pk %}">Vai alla recensione</a>
                <br>
            {% if user.is_authenticated and user == review.author %}
                <a href="{% url 'reviews:review-update' review.pk %}">Aggiorna recensione</a>
                <br>
                <a href="{% url 'reviews:review-delete' review.pk %}">Elimina recensione</a>
            {% endif %}
        </tr>
    {% endfor %}
{% endblock %}

{% block table_after %}
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Inizio</a>
            <a href="?page={{ page_obj.previous_page_number }}">Indietro</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Avanti</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Fine &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

digital_library/reviews/templates/reviews/personal_list.html
{% extends 'base_list.html' %}
{% load static %}

{% block list_title %}le mie recensioni{% endblock %}
{% block content_title %}Le mie recensioni{% endblock %}

{% block thead %}
    {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
    {% endif %}

    <th> </th>
    <th>Libro</th>
    <th>Voto</th>
    <th>Testo</th>
    <th>Data</th>
    <th>Dettaglio</th>
{% endblock %}

{% block tbody %}
    {% for review in page_obj %}
        <tr>
        <td>
            {% if review.book.pic %}
                    <img class="img-fluid img-thumbnail" src="{{ review.book.pic.url }}" style="width:85px">
                {% else %}
                    <img class="img-fluid img-thumbnail" src="{% static 'digital_lending/book-img-placeholder.jpg' %}" style="width:85px">
                {% endif %}
        </td>
            <td><a href="{% url 'digital_lending:edition-detail' review.book.pk %}">{{ review.book.book.title }}</a></td>
            <td>{{ review.rating }}</td>
            <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:1px;">{{ review.text }}</td>
            <td>{{ review.date_created|date }}</td>
            <td><a href="{% url 'reviews:review-detail' review.pk %}">Vai alla recensione</a>
                <br>
            {% if user.is_authenticated and user == review.author %}
                <a href="{% url 'reviews:review-update' review.pk %}">Aggiorna recensione</a>
                <br>
                <a href="{% url 'reviews:review-delete' review.pk %}">Elimina recensione</a>
            {% endif %}
        </tr>
    {% endfor %}
{% endblock %}

{% block table_after %}
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Inizio</a>
            <a href="?page={{ page_obj.previous_page_number }}">Indietro</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Avanti</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Fine &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

digital_library/reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Aggiorna recensione{% endblock %}

{% block content %}
    <h1><b>Aggiorna recensione</b></h1>
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <br>
        <a href="{% url 'reviews:review-detail' object.pk %}">Annulla</a>
        <input type="submit" value="Conferma">
    </form>
{% endblock %}