digital_library/accounts/urls.py
from django.urls import path

from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('', redirect_view),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/person/', PersonSignUpView.as_view(), name='person-signup'),
    path('signup/library/', LibrarySignUpView.as_view(), name='library-signup'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/library/<int:pk>/update/', LibraryProfileUpdateView.as_view(), name='library-update'),
    path('profile/add-library-cards', LibraryCardsCreateView.as_view(), name='library-cards-create'),
    path('profile/library-cards/list', LibraryCardsList.as_view(), name='library-cards-list'),
    path('profile/library-cards/<int:pk>/update', LibraryCardsUpdate.as_view(), name='library-cards-update'),
    path('profile/library-cards/<int:pk>/delete', LibraryCardsDelete.as_view(), name='library-cards-delete'),
]

digital_library/digital_lending/urls.py
from django.urls import path

from .views import *

app_name = 'digital_lending'

urlpatterns = [
    path('author/create', AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update', AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/detail', AuthorDetail.as_view(), name='author-detail'),
    path('book/create', BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update', BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/detail', BookDetail.as_view(), name='book-detail'),
    path('category/<int:pk>/detail', CategoryDetail.as_view(), name='category-detail'),
    path('publisher/create', PublisherCreate.as_view(), name='publisher-create'),
    path('publisher/<int:pk>/update', PublisherUpdate.as_view(), name='publisher-update'),
    path('publisher/<int:pk>/detail', PublisherDetail.as_view(), name='publisher-detail'),
    path('edition/create', EditionCreate.as_view(), name='edition-create'),
    path('periodical/create', PeriodicalCreate.as_view(), name='periodical-create'),
    path('periodical/<int:pk>/issue/create', PeriodicalIssueCreate.as_view(), name='issue-create'),
    path('edition/<int:pk>/update', EditionUpdate.as_view(), name='edition-update'),
    path('periodical/<int:pk>/update', PeriodicalUpdate.as_view(), name='periodical-update'),
    path('catalogue/', EditionList.as_view(), name='editions'),
    path('periodicals/', PeriodicalList.as_view(), name='periodicals'),
    path('edition/<int:pk>/detail', EditionDetail.as_view(), name='edition-detail'),
    path('edition/<int:pk>/copy-create', CopyCreate.as_view(), name='copy-create'),
    path('edition/<int:pk>/copies', CopyList.as_view(), name='copies'),
    path('edition/<int:pk>/choose-copy', ChooseCopyToLendView.as_view(), name='choose-copy'),
    path('library_catalogue', LibraryEditionsList.as_view(), name='library-catalogue'),
    path('library_periodicals', LibraryPeriodicalsList.as_view(), name='library-periodicals'),
    path('copy/<int:pk>/update', CopyUpdate.as_view(), name='copy-update'),
    path('copy/<int:pk>/delete', CopyDelete.as_view(), name='copy-delete'),
    path('periodical/<int:pk>/issues', PeriodicalIssueList.as_view(), name='periodical-issues'),
    path('issue/<int:pk>/update', PeriodicalIssueUpdate.as_view(), name='periodical-issue-update'),
    path('issue/<int:pk>/delete', PeriodicalIssueDelete.as_view(), name='periodical-issue-delete'),
    path('edition/<int:pk>/lend', LendBookView.as_view(), name='edition-lend'),
    path('edition/<int:pk>/reservation', BookReservationView.as_view(), name='edition-reservation'),
    path('edition/<int:pk>/favorite', BookFavoriteView.as_view(), name='edition-favorite'),
    path('edition/<int:pk>/add-to-list', AddBookToListView.as_view(), name='add-book-to-list'),
    path('edition/<int:pk>/delete-from-list', DeleteBookInList.as_view(), name='delete-book-from-list'),
    path('book-history', PersonBookHistoryList.as_view(), name='book-history'),
    path('book-reservations', PersonReservationList.as_view(), name='book-reservations'),
    path('book-reservations/<int:pk>/delete', ReservationDelete.as_view(), name='book-reservation-delete'),
    path('favorite-books', PersonFavoriteBooksList.as_view(), name='favorite-books'),
    path('favorite-books/<int:pk>/delete', FavoriteBookDelete.as_view(), name='favorite-book-delete'),
    path('book-list/create', BookListCreate.as_view(), name='book-list-create'),
    path('my-book-lists', UserBookLists.as_view(), name='my-book-lists'),
    path('my-saved-book-lists', UserSavedBookLists.as_view(), name='my-saved-book-lists'),
    path('book-lists', BookLists.as_view(), name='book-lists'),
    path('book-list/<int:pk>/detail', BookListDetail.as_view(), name='book-list-detail'),
    path('book-list/<int:pk>/update', BookListUpdate.as_view(), name='book-list-update'),
    path('book-list/<int:pk>/delete', BookListDelete.as_view(), name='book-list-delete'),
    path('book-list/<int:pk>/save', SaveBookListView.as_view(), name='book-list-save'),
    path('edition/<int:pk>/suggest-purchase', SuggestPurchaseView.as_view(), name='suggest-purchase'),
    path('purchase-suggestions/', LibraryPurchaseSuggestionsList.as_view(), name='purchase-suggestions'),
]

digital_library/digital_library/urls.py
import logging

from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from .views import Homepage, NotFound

_logger = logging.getLogger(__name__)

urlpatterns = [
    path('', Homepage.as_view(), name='home'),
    path('404-not-found', NotFound.as_view(), name='404-not-found'),
    path('reviews/', include('reviews.urls')),
    path('site/', include('digital_lending.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

digital_library/reviews/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'reviews'

urlpatterns = [
    path('edition/<int:pk>/reviews', ReviewListView.as_view(), name="review-list"),
    path('my-reviews', PersonReviewList.as_view(), name='my-reviews'),
    path('<int:pk>/detail', ReviewDetail.as_view(), name="review-detail"),
    path('edition/<int:pk>/add-review', ReviewCreateView.as_view(), name="review-create"),
    path('<int:pk>/update-review', ReviewUpdateView.as_view(), name="review-update"),
    path('<int:pk>/delete-review', ReviewDeleteView.as_view(), name="review-delete"),
    path('<int:pk>/upvote', ReviewUpvoteView.as_view(), name="review-upvote"),
    path('<int:pk>/downvote', ReviewDownvoteView.as_view(), name="review-downvote"),
]

digital_library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="io=edge">
    <title>{% block title %}{% endblock %}</title>
 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<link rel="stylesheet" type="text/css" href="https://www.w3schools.com/w3css/4/w3.css">

<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
{% block stylesheets %}{% endblock %}
</head>
<body>

    <!--NAVBAR-->
    <header class="page-header">
        <h1>Digital Library</h1>
    </header>

    <div id="navbar">
        <ul>
            <li><a href="{% url 'home' %}" class="btn btn-person btn-lg" role="button">Home</a></li>
            <li><a href="{% url 'accounts:signup' %}" class="btn btn-person btn-lg" role="button">Registrati</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:profile' user.pk %}" class="btn btn-person btn-lg" role="button">Profilo</a></li>
                <li><a href="{% url 'logout' %}" class="btn btn-person btn-lg" role="button">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}" class="btn btn-person btn-lg" role="button">Accedi</a></li>
            {% endif %}
            <li><a href="{% url 'digital_lending:editions' %}" class="btn btn-person btn-lg" role="button">Libri</a></li>
            <li><a href="{% url 'digital_lending:periodicals' %}" class="btn btn-person btn-lg" role="button">Periodici</a></li>
            <li><a href="{% url 'digital_lending:book-lists' %}" class="btn btn-person btn-lg" role="button">Liste</a></li>
            <li><a href="{% url 'admin:index' %}" class="btn btn-person btn-lg" role="button">Admin</a></li>
        </ul>
    </div>

    {% block content %}

    {% endblock %}
   <hr>
</body>
</html>

digital_library/templates/base_list.html
{% extends 'base.html' %}
{% block title %} {% block list_title %}{% endblock %}{% endblock %}

{% block content %}
    <h1><b>{% block content_title %}{% endblock %}</b></h1>
    <table class="table">
        <thead>
        <tr>
            {% block thead %}

            {% endblock %}
        </tr>
        </thead>
        <tbody>
        {% block tbody %}

        {% endblock %}
        </tbody>
    </table>
    {% block table_after %}

    {% endblock %}
{% endblock %}

digital_library/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Digital Library - Home page{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h3>Ciao, <a href="{% url 'accounts:profile' user.pk %}">{{ user.username }}</a>.</h3>
        {% if user.is_person %}
            {% if available_reserved_books %}
                <h4>I seguenti libri che avevi prenotato sono diventati disponibili:</h4>
                    <ul>
                        {% for edition in available_reserved_books %}
                            <li><a href="{% url 'digital_lending:edition-detail' edition.pk %}">{{ edition.book.title }}</a></li>
                        {% endfor %}
                    </ul>
            {% endif %}
        {% endif %}
    {% endif %}

     {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
    {% endif %}

    <hr>

    <h2><b>Libri: le ultime novità</b></h2>
    <li class="w3-bar">
        {% for edition in latest_book_editions %}
            {% if edition.pic %}
                <img src="{{ edition.pic.url }}" class="w3-bar-item w3-circle" style="width:85px">
            {% else %}
                <img src="{% static 'digital_lending/book-img-placeholder.jpg'%}" class="w3-bar-item w3-circle" style="width:85px">
            {% endif %}
                <div class="w3-bar-item">
                    <span class="w3-medium">
                        <b><a href="{% url 'digital_lending:edition-detail' edition.pk %}">{{ edition.book.title }}</a></b></span>
                        <br>
                        {% for author in edition.book.author.all %}
                            <span><a href="{% url 'digital_lending:author-detail' author.pk %}">{{ author.name }}</a></span>
                        {% endfor %}
              </div>
        {% endfor %}
    </li>

    <hr>

    <h2><b>Periodici: le ultime novità</b></h2>
    <li class="w3-bar">
        {% for issue in latest_periodical_issues %}
            {% if issue.periodical.pic %}
                <img src="{{ issue.periodical.pic.url }}" class="w3-bar-item w3-circle" style="width:85px">
            {% else %}
                <img src="{% static 'digital_lending/book-img-placeholder.jpg'%}" class="w3-bar-item w3-circle" style="width:85px">
            {% endif %}
                <div class="w3-bar-item">
                    <span class="w3-medium">
                        <b><a href="{% url 'digital_lending:periodical-issues' issue.periodical.pk %}">{{ issue.periodical.name }}</a></b></span>
                        <br>
                        N. {{ issue.number }}
                    <br>
                    <span><a href="{% url 'digital_lending:publisher-detail' issue.periodical.publisher.pk %}">{{ issue.periodical.publisher.name }}</a></span>
                </div>
        {% endfor %}
    </li>

    <hr>

    <h2><b>Liste: le ultime novità</b></h2>
    <li class="w3-bar">
        {% for list in latest_book_lists %}
            {% if list.books.all.0.edition.pic %}
                <img src="{{ list.books.all.0.edition.pic.url }}" class="w3-bar-item w3-circle" style="width:85px">
            {% else %}
                <img src="{% static 'digital_lending/book-img-placeholder.jpg'%}" class="w3-bar-item w3-circle" style="width:85px">
            {% endif %}
                <div class="w3-bar-item">
                    <span class="w3-medium">
                        <b><a href="{% url 'digital_lending:book-list-detail' list.pk %}">{{ list.title }}</a></b></span>
                        <br>
                        <span><a href="{% url 'accounts:profile' list.owner.pk %}">{{ list.owner.username }}</a></span>

                </div>
        {% endfor %}
    </li>

{% endblock %}