digital_library/accounts/urls.py
from django.urls import path

from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('', redirect_view),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/person/', PersonSignUpView.as_view(), name='person-signup'),
    path('signup/library/', LibrarySignUpView.as_view(), name='library-signup'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/library/<int:pk>/update/', LibraryProfileUpdateView.as_view(), name='library-update'),
    path('profile/add-library-cards', LibraryCardsCreateView.as_view(), name='library-cards-create'),
    path('profile/library-cards/list', LibraryCardsList.as_view(), name='library-cards-list'),
    path('profile/library-cards/<int:pk>/update', LibraryCardsUpdate.as_view(), name='library-cards-update'),
    path('profile/library-cards/<int:pk>/delete', LibraryCardsDelete.as_view(), name='library-cards-delete'),
]

digital_library/digital_lending/urls.py
from django.urls import path

from .views import *

app_name = 'digital_lending'

urlpatterns = [
    path('author/create', AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update', AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/detail', AuthorDetail.as_view(), name='author-detail'),
    path('book/create', BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update', BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/detail', BookDetail.as_view(), name='book-detail'),
    path('category/<int:pk>/detail', CategoryDetail.as_view(), name='category-detail'),
    path('publisher/create', PublisherCreate.as_view(), name='publisher-create'),
    path('publisher/<int:pk>/update', PublisherUpdate.as_view(), name='publisher-update'),
    path('publisher/<int:pk>/detail', PublisherDetail.as_view(), name='publisher-detail'),
    path('edition/create', EditionCreate.as_view(), name='edition-create'),
    path('periodical/create', PeriodicalCreate.as_view(), name='periodical-create'),
    path('periodical/<int:pk>/issue/create', PeriodicalIssueCreate.as_view(), name='issue-create'),
    path('edition/<int:pk>/update', EditionUpdate.as_view(), name='edition-update'),
    path('periodical/<int:pk>/update', PeriodicalUpdate.as_view(), name='periodical-update'),
    path('catalogue/', EditionList.as_view(), name='editions'),
    path('periodicals/', PeriodicalList.as_view(), name='periodicals'),
    path('edition/<int:pk>/detail', EditionDetail.as_view(), name='edition-detail'),
    path('edition/<int:pk>/copy-create', CopyCreate.as_view(), name='copy-create'),
    path('edition/<int:pk>/copies', CopyList.as_view(), name='copies'),
    path('edition/<int:pk>/choose-copy', ChooseCopyToLendView.as_view(), name='choose-copy'),
    path('library_catalogue', LibraryEditionsList.as_view(), name='library-catalogue'),
    path('library_periodicals', LibraryPeriodicalsList.as_view(), name='library-periodicals'),
    path('copy/<int:pk>/update', CopyUpdate.as_view(), name='copy-update'),
    path('copy/<int:pk>/delete', CopyDelete.as_view(), name='copy-delete'),
    path('periodical/<int:pk>/issues', PeriodicalIssueList.as_view(), name='periodical-issues'),
    path('issue/<int:pk>/update', PeriodicalIssueUpdate.as_view(), name='periodical-issue-update'),
    path('issue/<int:pk>/delete', PeriodicalIssueDelete.as_view(), name='periodical-issue-delete'),
    path('edition/<int:pk>/lend', LendBookView.as_view(), name='edition-lend'),
    path('edition/<int:pk>/reservation', BookReservationView.as_view(), name='edition-reservation'),
    path('edition/<int:pk>/favorite', BookFavoriteView.as_view(), name='edition-favorite'),
    path('edition/<int:pk>/add-to-list', AddBookToListView.as_view(), name='add-book-to-list'),
    path('edition/<int:pk>/delete-from-list', DeleteBookInList.as_view(), name='delete-book-from-list'),
    path('book-history', PersonBookHistoryList.as_view(), name='book-history'),
    path('book-reservations', PersonReservationList.as_view(), name='book-reservations'),
    path('book-reservations/<int:pk>/delete', ReservationDelete.as_view(), name='book-reservation-delete'),
    path('favorite-books', PersonFavoriteBooksList.as_view(), name='favorite-books'),
    path('favorite-books/<int:pk>/delete', FavoriteBookDelete.as_view(), name='favorite-book-delete'),
    path('book-list/create', BookListCreate.as_view(), name='book-list-create'),
    path('my-book-lists', UserBookLists.as_view(), name='my-book-lists'),
    path('my-saved-book-lists', UserSavedBookLists.as_view(), name='my-saved-book-lists'),
    path('book-lists', BookLists.as_view(), name='book-lists'),
    path('book-list/<int:pk>/detail', BookListDetail.as_view(), name='book-list-detail'),
    path('book-list/<int:pk>/update', BookListUpdate.as_view(), name='book-list-update'),
    path('book-list/<int:pk>/delete', BookListDelete.as_view(), name='book-list-delete'),
    path('book-list/<int:pk>/save', SaveBookListView.as_view(), name='book-list-save'),
    path('edition/<int:pk>/suggest-purchase', SuggestPurchaseView.as_view(), name='suggest-purchase'),
    path('purchase-suggestions/', LibraryPurchaseSuggestionsList.as_view(), name='purchase-suggestions'),
]

digital_library/digital_library/urls.py
import logging

from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from .views import Homepage, NotFound

_logger = logging.getLogger(__name__)

urlpatterns = [
    path('', Homepage.as_view(), name='home'),
    path('404-not-found', NotFound.as_view(), name='404-not-found'),
    path('reviews/', include('reviews.urls')),
    path('site/', include('digital_lending.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

digital_library/reviews/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'reviews'

urlpatterns = [
    path('edition/<int:pk>/reviews', ReviewListView.as_view(), name="review-list"),
    path('my-reviews', PersonReviewList.as_view(), name='my-reviews'),
    path('<int:pk>/detail', ReviewDetail.as_view(), name="review-detail"),
    path('edition/<int:pk>/add-review', ReviewCreateView.as_view(), name="review-create"),
    path('<int:pk>/update-review', ReviewUpdateView.as_view(), name="review-update"),
    path('<int:pk>/delete-review', ReviewDeleteView.as_view(), name="review-delete"),
    path('<int:pk>/upvote', ReviewUpvoteView.as_view(), name="review-upvote"),
    path('<int:pk>/downvote', ReviewDownvoteView.as_view(), name="review-downvote"),
]

digital_library/digital_lending/views/book_list_views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView, UpdateView
from django.views import View

from digital_lending.forms import *
from digital_lending.models import *
from digital_lending.utils import increment_list_view_count

from .resource_views import EntryCreate


class BookListCreate(EntryCreate):
    model = BookList
    template_name = 'digital_lending/resources/book_list/create.html'
    form_class = BookListForm
    success_url = reverse_lazy('digital_lending:my-book-lists')
    success_message = "Lista creata con successo!"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class UserBookLists(ListView):
    paginate_by = 6
    model = BookList
    template_name = 'digital_lending/resources/book_list/list.html'

    def get_queryset(self):
        return BookList.objects.filter(owner=User.objects.get(id=self.request.user.id)).order_by('id')


class UserSavedBookLists(ListView):
    paginate_by = 6
    model = SavedList
    template_name = 'digital_lending/resources/book_list/saved.html'

    def get_queryset(self):
        return SavedList.objects.filter(user=User.objects.get(id=self.request.user.id)).order_by('-date_saved')


class BookLists(ListView):
    paginate_by = 6
    model = BookList
    template_name = 'digital_lending/resources/book_list/list.html'

    def get_context_data(self, **kwargs):
        context = super(BookLists, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            user_saved_lists = SavedList.objects.filter(user=self.request.user).values_list('list_id', flat=True)
            context['user_saved_lists'] = user_saved_lists
        context['sort'] = self.request.GET.get('sort')
        return context

    def get_queryset(self):
        object_list = BookList.objects.filter(is_private=False)

        query = self.request.GET.get('q')
        if query:
            object_list = object_list.filter(title__icontains=query)

        edition = self.request.GET.get('edition')
        if edition:
            edition_in_lists = EditionInList.objects.filter(edition_id=edition)
            object_list = object_list.filter(id__in=edition_in_lists.values_list('list_id')).order_by('-date_created')

        order = self.request.GET.get("sort")
        if order == "oldest":
            object_list = object_list.order_by("date_created")
        else:
            object_list = object_list.order_by("-date_created")

        return object_list


class BookListDetail(DetailView):
    model = BookList
    template_name = 'digital_lending/resources/book_list/detail.html'

    def get(self, request, *args, **kwargs):
        increment_list_view_count(self.kwargs['pk'])
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(BookListDetail, self).get_context_data(**kwargs)
        context['list'] = BookList.objects.get(id=self.kwargs['pk'])
        context['views'] = BookList.objects.get(id=self.kwargs['pk']).views

        order = self.request.GET.get("sort")

        if order == "oldest":
            context['editions'] = BookList.objects.get(id=self.kwargs['pk']).books.all().order_by("date_added")
        elif order == "title_asc":
            context['editions'] = BookList.objects.get(id=self.kwargs['pk']).books.all().order_by("-edition__book__title")
        elif order == "title_desc":
            context['editions'] = BookList.objects.get(id=self.kwargs['pk']).books.all().order_by("edition__book__title")
        else:
            context['editions'] = BookList.objects.get(id=self.kwargs['pk']).books.all().order_by("-date_added")
        context['sort'] = self.request.GET.get('sort')
        return context


class BookListUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = BookList
    template_name = 'digital_lending/resources/book_list/update.html'
    success_url = reverse_lazy('digital_lending:my-book-lists')
    form_class = BookListForm
    success_message = 'Lista aggiornata con successo!'

    def get_object(self, *args, **kwargs):
        obj = super(BookListUpdate, self).get_object(*args, **kwargs)
        if not obj.owner_id == self.request.user.id:
            raise PermissionDenied
        return obj


class BookListDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = BookList
    template_name = 'digital_lending/resources/book_list/delete.html'
    success_url = reverse_lazy('digital_lending:my-book-lists')
    success_message = 'Lista eliminata con successo!'

    def get_object(self, *args, **kwargs):
        obj = super(BookListDelete, self).get_object(*args, **kwargs)
        if not obj.owner_id == self.request.user.id:
            raise PermissionDenied
        return obj


class AddBookToListView(EntryCreate):
    model = EditionInList
    template_name = 'digital_lending/resources/book_list/edition_entry/create.html'
    form_class = AddBookToListForm
    success_message = 'Il libro è stato aggiunto alla lista!'

    def get_success_url(self):
        pk = self.object.edition.isbn_digital
        return reverse_lazy('digital_lending:edition-detail', kwargs={'pk': pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(AddBookToListView, self).get_context_data(**kwargs)
        context['edition'] = Edition.objects.get(isbn_digital=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.edition = Edition.objects.get(isbn_digital=self.kwargs['pk'])
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        try:
            return super().post(request, *args, **kwargs)
        except IntegrityError:
            messages.add_message(request, messages.ERROR,
                                 'Hai già inserito questo libro nella lista.')
            return render(request, template_name=self.template_name, context=self.get_context_data())


class DeleteBookInList(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = EditionInList
    template_name = 'digital_lending/resources/book_list/edition_entry/delete.html'
    success_message = 'Il libro è stato eliminato dalla lista!'

    def get_success_url(self):
        pk = self.object.list.id
        return reverse_lazy('digital_lending:book-list-detail', kwargs={'pk': pk})

    def get_object(self, *args, **kwargs):
        obj = super(DeleteBookInList, self).get_object(*args, **kwargs)
        if not obj.list.owner_id == self.request.user.id:
            raise PermissionDenied
        return obj


class SaveBookListView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        obj, created = SavedList.objects.get_or_create(
            user=User.objects.get(id=self.request.user.id),
            list=BookList.objects.get(id=self.kwargs['pk']))
        if not created:
            obj.delete()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

digital_library/digital_lending/templates/digital_lending/resources/book_list/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Crea una nuova lista{% endblock %}

{% block content %}
    {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
    {% endif %}

    <h1><b>Crea una nuova lista</b></h1>
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <br>
        <a href="{% url 'digital_lending:my-book-lists' %}">Annulla</a>
        <input type="submit" value="Conferma">
    </form>
{% endblock %}

digital_library/digital_lending/templates/digital_lending/resources/book_list/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Elimina lista "{{ object.title }}"{% endblock %}

{% block content %}
    <h1><b>Elimina lista "{{ object.title }}"</b></h1>
    <br>
    <h4>Confermi di voler eliminare questa lista?</h4>
    <h5><b>Titolo:</b> {{ object.title }}</h5>
    <h5><b>Descrizione:</b>{% if object.desc %} {{ object.desc }} {% else %} - {% endif %}</h5>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <a href="{% url 'digital_lending:my-book-lists' %}">Annulla</a>
        <input type="submit" value="Conferma">
    </form>
{% endblock %}

digital_library/digital_lending/templates/digital_lending/resources/book_list/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Lista: {{ list.title }}{% endblock %}

{% block content %}
    {% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
    {% endif %}

    <h1><b>Lista: {{ list.title }} di <a href="{% url 'accounts:profile' list.owner.pk %}">{{ list.owner.username }}</a></b></h1>
    <br>
    <h4>{% if list.desc %}{{ list.desc }} {% else %}  {% endif %}</h4>
    <br>
    <h5><b>{{ views }}</b> visualizzazioni</h5>
     <table class="table">
        <thead>
        <tr>
            <th> </th>
            <th>Titolo
                {% if sort == "title_desc" or "" %}
                    <a href="{% url 'digital_lending:book-list-detail' list.pk %}?sort=title_asc">▼</a>
                {% else %}
                    <a href="{% url 'digital_lending:book-list-detail' list.pk %}?sort=title_desc">▲</a>
                {% endif %}
            </th>
            <th>Autore</th>
            <th>Data aggiunto
                {% if sort == "oldest" or "" %}
                    <a href="{% url 'digital_lending:book-list-detail' list.pk %}?sort=newest">▼</a>
                {% else %}
                    <a href="{% url 'digital_lending:book-list-detail' list.pk %}?sort=oldest">▲</a>
                {% endif %}
            </th>
            <th>Dettaglio</th>
        </tr>
        </thead>
        <tbody>
           {% for entry in editions %}
               <tr>
               <td>
                   {% if entry.edition.pic %}
                    <img class="img-fluid img-thumbnail" src="{{ entry.edition.pic.url }}" style="width:85px">
                {% else %}
                    <img class="img-fluid img-thumbnail" src="{% static 'digital_lending/book-img-placeholder.jpg' %}" style="width:85px">
                {% endif %}
               </td>
                <td>{{ entry.edition.book.title }}</td>
                <td>
                    {% for author in entry.edition.book.author.all %}
                        <a href="{% url 'digital_lending:author-detail' author.pk %}">{{ author.name }}</a>
                    {% endfor %}
                </td>
                <td>{{ entry.date_added|date }}</td>
                <td><a href="{% url 'digital_lending:edition-detail' entry.edition.isbn_digital %}">Vai al libro</a>
               <br>
                    {% if user.is_authenticated and user == list.owner %}
                        <a href="{% url 'digital_lending:delete-book-from-list' entry.pk %}">Elimina libro</a></td>
                    {% endif %}

               </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if user.is_authenticated and list.owner == user %}
        <br>
        <a href="{% url 'digital_lending:book-list-update' list.pk %}" class="w3-button w3-teal w3-round-large" role="button">Aggiorna lista</a>
        <br><br>
        <a href="{% url 'digital_lending:book-list-delete' list.pk %}" class="w3-button w3-teal w3-round-large" role="button">Elimina lista</a>
    {% endif %}

    <hr>
{% endblock %}

digital_library/digital_lending/templates/digital_lending/resources/book_list/list.html
{% extends 'base_list.html' %}
{% load static %}

{% block list_title %}Liste{% endblock %}
{% block content_title %}
    <h5>{% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}">
             {{ message|safe }}
         </div>
     {% endfor %}
    {% endif %}</h5>

    <h1><b>Liste</b></h1>
{% endblock %}

{% block thead %}
    <form action="{% url 'digital_lending:book-lists' %}" method="get">
        <input name="q" type="text" placeholder="Cerca titolo...">
    </form>
    <br>
    <th> </th>
    <th>Titolo</th>
    <th>Utente</th>
    <th>Data creazione
        {% if sort == "oldest" or sort == "" %}
            <a href="{% url 'digital_lending:book-lists' %}?sort=newest">▼</a>
        {% else %}
            <a href="{% url 'digital_lending:book-lists' %}?sort=oldest">▲</a>
    {% endif %}
    </th>
    <th>Dettaglio</th>
    <th>Salva</th>
{% endblock %}

{% block tbody %}
    {% for list in page_obj %}
        <tr>
            <td>
                {% if list.books.all.0.edition.pic %}
                    <img class="img-fluid img-thumbnail" src="{{ list.books.all.0.edition.pic.url }}" style="width:85px">
                {% else %}
                    <img class="img-fluid img-thumbnail" src="{% static 'digital_lending/book-img-placeholder.jpg' %}" style="width:85px">
                {% endif %}
            </td>
            <td>{{ list.title }}</td>
            <td>
                <a href="{% url 'accounts:profile' list.owner.pk %}">{{ list.owner.username }}</a>
            </td>
            <td>{{ list.date_created|date }}</td>
            <td><a href="{% url 'digital_lending:book-list-detail' list.pk %}">Vai alla lista</a>
                {% if user.is_authenticated and list.owner == user %}
                <br>
                <a href="{% url 'digital_lending:book-list-update' list.pk %}">Aggiorna lista</a>
                <br>
                <a href="{% url 'digital_lending:book-list-delete' list.pk %}">Elimina lista</a>
                {% endif %}
            </td>
            <td>
                {% if user.is_authenticated and list.owner != user %}
                    <form method="POST" action="{% url 'digital_lending:book-list-save' list.pk %}" class="form-check-inline">
                        {% csrf_token %}
                        <button type="submit" class="w3-button w3-teal w3-round-large">
                            {% if list.pk in user_saved_lists %}Rimuovi lista {% else %} Salva lista {% endif %}</button>
                    </form>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
{% endblock %}

{% block table_after %}
    {% if user.is_authenticated %}
        <a href="{% url 'digital_lending:book-list-create' %}" class="w3-button w3-teal w3-round-large" role="button">Crea una nuova lista</a>
    {%  endif %}
    <hr>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Inizio</a>
            <a href="?page={{ page_obj.previous_page_number }}">Indietro</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Avanti</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Fine &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

digital_library/digital_lending/templates/digital_lending/resources/book_list/saved.html
{% extends 'base_list.html' %}
{% load static %}

{% block list_title %}Liste salvate{% endblock %}
{% block content_title %}Liste salvate{% endblock %}

{% block thead %}
    <th> </th>
    <th>Titolo</th>
    <th>Utente</th>
    <th>Descrizione</th>
    <th>Dettaglio</th>
    <th>Opzioni</th>
{% endblock %}

{% block tbody %}
    {% for saved_list in page_obj %}
        <tr>
            <td>
                {% if saved_list.books.all.0.edition.picedition.pic %}
                    <img class="img-fluid img-thumbnail" src="{{ saved_list.books.all.0.edition.pic.url }}" style="width:85px">
                {% else %}
                    <img class="img-fluid img-thumbnail" src="{% static 'digital_lending/book-img-placeholder.jpg' %}" style="width:85px">
                {% endif %}
            </td>
            <td>{{ saved_list.list.title }}</td>
            <td><a href="{% url 'accounts:profile' saved_list.list.owner.pk %}">{{ saved_list.list.owner.username }}</a></td>
            <td style="white-space: nowrap; text-overflow:ellipsis; overflow: hidden; max-width:1px;">
                {% if saved_list.list.desc %}{{ saved_list.list.desc }} {% else %} - {% endif %}
            </td>
        <td>
            <a href="{% url 'digital_lending:book-list-detail' saved_list.list.pk %}">Vai alla lista</a>
        </td>
            <td>
                <form method="POST" action="{% url 'digital_lending:book-list-save' saved_list.list.pk %}" class="form-check-inline">
                        {% csrf_token %}
                        <button type="submit" class="w3-button w3-teal w3-round-large" role="button" >Rimuovi lista</button>
                </form>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

{% block table_after %}
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Inizio</a>
            <a href="?page={{ page_obj.previous_page_number }}">Indietro</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Avanti</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Fine &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

digital_library/digital_lending/templates/digital_lending/resources/book_list/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Aggiorna lista "{{ object.title }}"{% endblock %}

{% block content %}
    <h1><b>Aggiorna lista "{{ object.title }}"</b></h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <a href="{% url 'digital_lending:my-book-lists' %}">Annulla</a>
        <input type="submit" value="Conferma">
    </form>
{% endblock %}